export interface Question {
  id: string;
  text: string;
  category: 'Deep' | 'Funny' | 'What If' | 'Close People' | 'Would You Rather';
  intensity: number;
}

export const CATEGORIES = ['All', 'Deep', 'Funny', 'What If', 'Close People', 'Would You Rather'] as const;

export type Category = typeof CATEGORIES[number];

export const QUESTIONS: Question[] = [
  // --- DEEP (1-60) ---
  { id: '1', text: "What's a belief you hold that most people disagree with?", category: 'Deep', intensity: 3 },
  { id: '2', text: "If you could instantly become an expert in one subject, what would it be?", category: 'Deep', intensity: 2 },
  { id: '3', text: "What is the most unexplainable thing that has ever happened to you?", category: 'Deep', intensity: 3 },
  { id: '4', text: "What is the meaning of life in your own words?", category: 'Deep', intensity: 3 },
  { id: '5', text: "What is your definition of true success?", category: 'Deep', intensity: 2 },
  { id: '6', text: "What is your biggest regret so far?", category: 'Deep', intensity: 3 },
  { id: '7', text: "What is your proudest accomplishment?", category: 'Deep', intensity: 2 },
  { id: '8', text: "If you could change one decision from your past, what would it be?", category: 'Deep', intensity: 3 },
  { id: '9', text: "Do you fear death, or just not living fully?", category: 'Deep', intensity: 3 },
  { id: '10', text: "Do you believe in soulmates?", category: 'Deep', intensity: 2 },
  { id: '11', text: "What do you think exists at the edge of the universe?", category: 'Deep', intensity: 3 },
  { id: '12', text: "Is human nature inherently good or evil?", category: 'Deep', intensity: 3 },
  { id: '13', text: "What childhood event impacted you the most?", category: 'Deep', intensity: 3 },
  { id: '14', text: "What is your biggest rational or irrational fear?", category: 'Deep', intensity: 2 },
  { id: '15', text: "Can people truly change their core personality?", category: 'Deep', intensity: 2 },
  { id: '16', text: "Is it better to forgive and forget, or just forgive?", category: 'Deep', intensity: 2 },
  { id: '17', text: "What is your definition of love?", category: 'Deep', intensity: 3 },
  { id: '18', text: "What makes a person truly evil?", category: 'Deep', intensity: 3 },
  { id: '19', text: "What makes a person truly good?", category: 'Deep', intensity: 2 },
  { id: '20', text: "Does art need a meaning to be valuable?", category: 'Deep', intensity: 2 },
  { id: '21', text: "Why do we repeat history if we study it so much?", category: 'Deep', intensity: 3 },
  { id: '22', text: "Is technology connecting us or isolating us?", category: 'Deep', intensity: 2 },
  { id: '23', text: "Do you think we are alone in the universe?", category: 'Deep', intensity: 2 },
  { id: '24', text: "What do you think a soul actually is?", category: 'Deep', intensity: 3 },
  { id: '25', text: "Do humans actually have free will?", category: 'Deep', intensity: 3 },
  { id: '26', text: "Is beauty objective or purely subjective?", category: 'Deep', intensity: 2 },
  { id: '27', text: "How much of success is just pure luck?", category: 'Deep', intensity: 2 },
  { id: '28', text: "How should a society measure a life's worth?", category: 'Deep', intensity: 3 },
  { id: '29', text: "What does true freedom look like to you?", category: 'Deep', intensity: 3 },
  { id: '30', text: "Does absolute power always corrupt?", category: 'Deep', intensity: 2 },
  { id: '31', text: "What is the most beautiful place you have ever seen?", category: 'Deep', intensity: 1 },
  { id: '32', text: "What is the best piece of advice you've ever received?", category: 'Deep', intensity: 2 },
  { id: '33', text: "What is the hardest lesson you've had to learn?", category: 'Deep', intensity: 3 },
  { id: '34', text: "What would you tell your 10-year-old self?", category: 'Deep', intensity: 2 },
  { id: '35', text: "How do you personally handle grief?", category: 'Deep', intensity: 3 },
  { id: '36', text: "What is the biggest sacrifice you've made for someone?", category: 'Deep', intensity: 3 },
  { id: '37', text: "What is a cause you would willingly die for?", category: 'Deep', intensity: 3 },
  { id: '38', text: "What is the one thing you truly live for?", category: 'Deep', intensity: 3 },
  { id: '39', text: "What does family mean to you?", category: 'Deep', intensity: 2 },
  { id: '40', text: "What does friendship mean to you?", category: 'Deep', intensity: 2 },
  { id: '41', text: "How do you find purpose when feeling lost?", category: 'Deep', intensity: 3 },
  { id: '42', text: "How do you deal with things you can't control?", category: 'Deep', intensity: 3 },
  { id: '43', text: "What brings you the most genuine, unadulterated joy?", category: 'Deep', intensity: 2 },
  { id: '44', text: "How do you face the things that terrify you?", category: 'Deep', intensity: 3 },
  { id: '45', text: "What is your definition of true courage?", category: 'Deep', intensity: 2 },
  { id: '46', text: "What is the difference between intelligence and wisdom?", category: 'Deep', intensity: 2 },
  { id: '47', text: "At what age do we lose our innocence?", category: 'Deep', intensity: 3 },
  { id: '48', text: "Is it possible to remain uncorrupted by society?", category: 'Deep', intensity: 3 },
  { id: '49', text: "Have you ever felt truly betrayed?", category: 'Deep', intensity: 3 },
  { id: '50', text: "What does loyalty look like in practice?", category: 'Deep', intensity: 2 },
  { id: '51', text: "Where do you find hope in dark times?", category: 'Deep', intensity: 3 },
  { id: '52', text: "Do you believe everything happens for a reason?", category: 'Deep', intensity: 2 },
  { id: '53', text: "What makes a life meaningful?", category: 'Deep', intensity: 3 },
  { id: '54', text: "How do you want to be remembered after you die?", category: 'Deep', intensity: 3 },
  { id: '55', text: "What is the biggest lie humanity tells itself?", category: 'Deep', intensity: 3 },
  { id: '56', text: "Is perfection an illusion or a goal?", category: 'Deep', intensity: 2 },
  { id: '57', text: "Do we outgrow people, or do they outgrow us?", category: 'Deep', intensity: 2 },
  { id: '58', text: "What is the most destructive human emotion?", category: 'Deep', intensity: 3 },
  { id: '59', text: "Can suffering ever be a good thing?", category: 'Deep', intensity: 3 },
  { id: '60', text: "If you could ask the universe one question, what would it be?", category: 'Deep', intensity: 3 },

  // --- FUNNY (61-120) ---
  { id: '61', text: "What's the worst haircut you ever had?", category: 'Funny', intensity: 1 },
  { id: '62', text: "If animals could talk, which would be the rudest?", category: 'Funny', intensity: 1 },
  { id: '63', text: "What is a completely rational fear you have that sounds silly?", category: 'Funny', intensity: 1 },
  { id: '64', text: "What is the weirdest food combination you secretly enjoy?", category: 'Funny', intensity: 1 },
  { id: '65', text: "What is the stupidest argument you've ever been in?", category: 'Funny', intensity: 2 },
  { id: '66', text: "What is your most useless, bizarre talent?", category: 'Funny', intensity: 1 },
  { id: '67', text: "What was your absolute worst fashion choice?", category: 'Funny', intensity: 1 },
  { id: '68', text: "What is the weirdest dream you've ever had?", category: 'Funny', intensity: 2 },
  { id: '69', text: "What is the most awkward text you've ever sent by mistake?", category: 'Funny', intensity: 2 },
  { id: '70', text: "What is the worst date you've ever been on?", category: 'Funny', intensity: 2 },
  { id: '71', text: "What is the funniest joke you know by heart?", category: 'Funny', intensity: 1 },
  { id: '72', text: "What is your weirdest, most specific phobia?", category: 'Funny', intensity: 1 },
  { id: '73', text: "What is the worst smell in the world?", category: 'Funny', intensity: 1 },
  { id: '74', text: "What is a weird habit you do when no one is watching?", category: 'Funny', intensity: 2 },
  { id: '75', text: "What is the dumbest way you've ever injured yourself?", category: 'Funny', intensity: 2 },
  { id: '76', text: "What is the worst lie you told as a kid?", category: 'Funny', intensity: 2 },
  { id: '77', text: "What movie always makes you laugh out loud?", category: 'Funny', intensity: 1 },
  { id: '78', text: "What is the worst song to play at a funeral?", category: 'Funny', intensity: 2 },
  { id: '79', text: "Who was your weirdest childhood celebrity crush?", category: 'Funny', intensity: 1 },
  { id: '80', text: "What is your most embarrassing moment in public?", category: 'Funny', intensity: 2 },
  { id: '81', text: "If you were a potato, what kind of potato dish would you be?", category: 'Funny', intensity: 1 },
  { id: '82', text: "Would you rather fight 1 duck-sized horse or 100 horse-sized ducks?", category: 'Funny', intensity: 1 },
  { id: '83', text: "What is objectively the worst pizza topping?", category: 'Funny', intensity: 1 },
  { id: '84', text: "Where is the weirdest place you've ever fallen asleep?", category: 'Funny', intensity: 1 },
  { id: '85', text: "What is the dumbest thing you've ever spent money on?", category: 'Funny', intensity: 1 },
  { id: '86', text: "What is the worst piece of advice you've actually followed?", category: 'Funny', intensity: 2 },
  { id: '87', text: "What is the worst gift you have ever given someone?", category: 'Funny', intensity: 1 },
  { id: '88', text: "What is the funniest misunderstanding you've been a part of?", category: 'Funny', intensity: 2 },
  { id: '89', text: "What is the weirdest thing currently in your fridge?", category: 'Funny', intensity: 1 },
  { id: '90', text: "What was your most embarrassing teenage phase?", category: 'Funny', intensity: 2 },
  { id: '91', text: "What is the dumbest rule you broke just for the thrill?", category: 'Funny', intensity: 2 },
  { id: '92', text: "What is the worst typo you've ever made in a professional setting?", category: 'Funny', intensity: 2 },
  { id: '93', text: "What is a funny animal video you watch when you're sad?", category: 'Funny', intensity: 1 },
  { id: '94', text: "What is a weird noise you can make with your body?", category: 'Funny', intensity: 1 },
  { id: '95', text: "What was your dumbest fear as a kid?", category: 'Funny', intensity: 1 },
  { id: '96', text: "What is a weird smell that you secretly like?", category: 'Funny', intensity: 1 },
  { id: '97', text: "If you could have a completely useless superpower, what would it be?", category: 'Funny', intensity: 1 },
  { id: '98', text: "What is the funniest sounding word in the English language?", category: 'Funny', intensity: 1 },
  { id: '99', text: "What is the worst nickname you've ever been given?", category: 'Funny', intensity: 1 },
  { id: '100', text: "If dogs wore pants, would they wear them on 2 legs or 4?", category: 'Funny', intensity: 1 },
  { id: '101', text: "Is cereal just cold soup?", category: 'Funny', intensity: 1 },
  { id: '102', text: "Is a hotdog technically a sandwich?", category: 'Funny', intensity: 1 },
  { id: '103', text: "Is water wet, or does it just make things wet?", category: 'Funny', intensity: 1 },
  { id: '104', text: "What is the worst ice cream flavor imaginable?", category: 'Funny', intensity: 1 },
  { id: '105', text: "What is the funniest WiFi network name you've seen?", category: 'Funny', intensity: 1 },
  { id: '106', text: "What would be the worst tagline for your life movie?", category: 'Funny', intensity: 2 },
  { id: '107', text: "What is the weirdest thing to say at a wedding?", category: 'Funny', intensity: 2 },
  { id: '108', text: "What is the dumbest way to get yourself arrested?", category: 'Funny', intensity: 1 },
  { id: '109', text: "What is the worst possible thing to say on a first date?", category: 'Funny', intensity: 2 },
  { id: '110', text: "What is your favorite highly specific insult?", category: 'Funny', intensity: 2 },
  { id: '111', text: "What is the weirdest compliment you've ever received?", category: 'Funny', intensity: 1 },
  { id: '112', text: "What is the worst thing to find inside your shoe?", category: 'Funny', intensity: 1 },
  { id: '113', text: "Can you make a funny face right now?", category: 'Funny', intensity: 1 },
  { id: '114', text: "What is the worst place to try and play hide and seek?", category: 'Funny', intensity: 1 },
  { id: '115', text: "What is the weirdest object you would put in a frame?", category: 'Funny', intensity: 1 },
  { id: '116', text: "What is the worst item to drop in a public toilet?", category: 'Funny', intensity: 1 },
  { id: '117', text: "What is the weirdest thing to yell in a quiet room?", category: 'Funny', intensity: 2 },
  { id: '118', text: "What is the weirdest thing you've seen in someone else's home?", category: 'Funny', intensity: 1 },
  { id: '119', text: "If you could only eat one meal forever, what would it be?", category: 'Funny', intensity: 1 },
  { id: '120', text: "If you had a warning label on your forehead, what would it say?", category: 'Funny', intensity: 2 },

  // --- WHAT IF (121-180) ---
  { id: '121', text: "What if you had to live the exact same day over and over forever?", category: 'What If', intensity: 3 },
  { id: '122', text: "What if gravity suddenly reversed for 5 seconds every day?", category: 'What If', intensity: 2 },
  { id: '123', text: "What if you woke up tomorrow and everyone else had vanished?", category: 'What If', intensity: 3 },
  { id: '124', text: "What if you could see 10 years into the future, but couldn't change it?", category: 'What If', intensity: 3 },
  { id: '125', text: "What if you could pause time, but only for 10 minutes a day?", category: 'What If', intensity: 2 },
  { id: '126', text: "What if you could rewind time 5 minutes, but only once a week?", category: 'What If', intensity: 2 },
  { id: '127', text: "What if you could read minds, but only when people are thinking about food?", category: 'What If', intensity: 1 },
  { id: '128', text: "What if humans suddenly grew wings, how would society change?", category: 'What If', intensity: 2 },
  { id: '129', text: "What if you could become completely invisible, but only when you hold your breath?", category: 'What If', intensity: 1 },
  { id: '130', text: "What if you could breathe underwater, where would you explore?", category: 'What If', intensity: 2 },
  { id: '131', text: "What if you could teleport anywhere, but you arrive completely naked?", category: 'What If', intensity: 2 },
  { id: '132', text: "What if you could talk to the dead, but they only complain?", category: 'What If', intensity: 2 },
  { id: '133', text: "What if humans never needed to sleep?", category: 'What If', intensity: 2 },
  { id: '134', text: "What if you could eat anything without gaining weight?", category: 'What If', intensity: 1 },
  { id: '135', text: "What if you never aged past 25?", category: 'What If', intensity: 2 },
  { id: '136', text: "What if you could change one law globally?", category: 'What If', intensity: 3 },
  { id: '137', text: "What if you had the power to ban one word from existence?", category: 'What If', intensity: 1 },
  { id: '138', text: "What if aliens arrived and they were microscopic?", category: 'What If', intensity: 2 },
  { id: '139', text: "What if the internet permanently shut down tomorrow?", category: 'What If', intensity: 3 },
  { id: '140', text: "What if dinosaurs suddenly returned to the earth?", category: 'What If', intensity: 2 },
  { id: '141', text: "What if the moon exploded tonight?", category: 'What If', intensity: 3 },
  { id: '142', text: "What if the sun never set on your city?", category: 'What If', intensity: 2 },
  { id: '143', text: "What if all water suddenly tasted like maple syrup?", category: 'What If', intensity: 1 },
  { id: '144', text: "What if everyone in the world woke up blind?", category: 'What If', intensity: 3 },
  { id: '145', text: "What if music completely ceased to exist?", category: 'What If', intensity: 3 },
  { id: '146', text: "What if everyone had to literally sing instead of talk?", category: 'What If', intensity: 1 },
  { id: '147', text: "What if everyone was forced to tell the truth at all times?", category: 'What If', intensity: 3 },
  { id: '148', text: "What if money was suddenly abolished?", category: 'What If', intensity: 3 },
  { id: '149', text: "What if humans regularly lived to be 500 years old?", category: 'What If', intensity: 3 },
  { id: '150', text: "What if all diseases were suddenly cured overnight?", category: 'What If', intensity: 2 },
  { id: '151', text: "What if every person gets a superpower based on their worst trait?", category: 'What If', intensity: 2 },
  { id: '152', text: "What if a zombie apocalypse started right now?", category: 'What If', intensity: 2 },
  { id: '153', text: "What if AI robots took over, but they were super polite?", category: 'What If', intensity: 1 },
  { id: '154', text: "What if plants could scream when you cut them?", category: 'What If', intensity: 2 },
  { id: '155', text: "What if the sky was permanently neon red?", category: 'What If', intensity: 1 },
  { id: '156', text: "What if the oceans suddenly dried up?", category: 'What If', intensity: 3 },
  { id: '157', text: "What if you woke up tomorrow as a domestic house cat?", category: 'What If', intensity: 1 },
  { id: '158', text: "What if you were the president of the world for one week?", category: 'What If', intensity: 2 },
  { id: '159', text: "What if you found a briefcase with a million untraceable dollars?", category: 'What If', intensity: 2 },
  { id: '160', text: "What if you had to live alone on a Mars colony?", category: 'What If', intensity: 3 },
  { id: '161', text: "What if you were the last person on earth, but you weren't alone?", category: 'What If', intensity: 3 },
  { id: '162', text: "What if you found a genie but he was actively trying to ruin your wishes?", category: 'What If', intensity: 2 },
  { id: '163', text: "What if your life was secretly a reality TV show?", category: 'What If', intensity: 2 },
  { id: '164', text: "What if you got trapped inside your favorite video game?", category: 'What If', intensity: 2 },
  { id: '165', text: "What if you had a time machine that only went to the year 1800?", category: 'What If', intensity: 2 },
  { id: '166', text: "What if you found a magic wand that only cast annoying spells?", category: 'What If', intensity: 1 },
  { id: '167', text: "What if you became a ghost who could only haunt one specific building?", category: 'What If', intensity: 2 },
  { id: '168', text: "What if you could shape-shift into any animal, but keep human intelligence?", category: 'What If', intensity: 2 },
  { id: '169', text: "What if you could control the weather with your emotions?", category: 'What If', intensity: 2 },
  { id: '170', text: "What if you could instantly heal people, but take on their pain?", category: 'What If', intensity: 3 },
  { id: '171', text: "What if you could erase any memory from your mind?", category: 'What If', intensity: 3 },
  { id: '172', text: "What if you could create any object out of thin air once a day?", category: 'What If', intensity: 2 },
  { id: '173', text: "What if you could destroy anything with a touch?", category: 'What If', intensity: 2 },
  { id: '174', text: "What if you could fly, but only as fast as you can run?", category: 'What If', intensity: 1 },
  { id: '175', text: "What if you could run at light speed, but it ruined your clothes?", category: 'What If', intensity: 1 },
  { id: '176', text: "What if animals judged us based on our actions?", category: 'What If', intensity: 2 },
  { id: '177', text: "What if all conspiracy theories turned out to be completely true?", category: 'What If', intensity: 3 },
  { id: '178', text: "What if humans laid eggs instead of live birth?", category: 'What If', intensity: 1 },
  { id: '179', text: "What if the earth was actually flat this whole time?", category: 'What If', intensity: 1 },
  { id: '180', text: "What if we are all living in a hyper-realistic simulation?", category: 'What If', intensity: 3 },

  // --- CLOSE PEOPLE (181-240) ---
  { id: '181', text: "What is a memory with me that you'll never forget?", category: 'Close People', intensity: 3 },
  { id: '182', text: "In what ways do you think we are most alike?", category: 'Close People', intensity: 2 },
  { id: '183', text: "What's something you've always wanted to ask me but haven't?", category: 'Close People', intensity: 3 },
  { id: '184', text: "What was your actual first impression of me?", category: 'Close People', intensity: 2 },
  { id: '185', text: "What do you think is my absolutely best trait?", category: 'Close People', intensity: 2 },
  { id: '186', text: "What do you think is my worst or most annoying habit?", category: 'Close People', intensity: 2 },
  { id: '187', text: "What is the best trip or outing we have ever taken together?", category: 'Close People', intensity: 1 },
  { id: '188', text: "What is the funniest moment we have ever shared?", category: 'Close People', intensity: 1 },
  { id: '189', text: "What is the worst fight or disagreement we've had, and how did we grow?", category: 'Close People', intensity: 3 },
  { id: '190', text: "What is our absolute best inside joke?", category: 'Close People', intensity: 1 },
  { id: '191', text: "What is one specific thing you admire about me?", category: 'Close People', intensity: 2 },
  { id: '192', text: "What is something important that I have taught you?", category: 'Close People', intensity: 3 },
  { id: '193', text: "What is something important that you have taught me?", category: 'Close People', intensity: 3 },
  { id: '194', text: "How have I changed since the day we first met?", category: 'Close People', intensity: 3 },
  { id: '195', text: "How do you think you've changed since we met?", category: 'Close People', intensity: 3 },
  { id: '196', text: "What is your biggest hope for my future?", category: 'Close People', intensity: 3 },
  { id: '197', text: "What is a fear you hold regarding my future?", category: 'Close People', intensity: 3 },
  { id: '198', text: "What is something you wish we did more of together?", category: 'Close People', intensity: 2 },
  { id: '199', text: "What is something you wish we did less of?", category: 'Close People', intensity: 2 },
  { id: '200', text: "What is the thing you love most about our relationship?", category: 'Close People', intensity: 3 },
  { id: '201', text: "When was the exact moment you knew we were going to be close?", category: 'Close People', intensity: 3 },
  { id: '202', text: "What do you think is my weirdest quirk?", category: 'Close People', intensity: 1 },
  { id: '203', text: "What is a hidden talent you know I have?", category: 'Close People', intensity: 2 },
  { id: '204', text: "What do you honestly think is my biggest flaw?", category: 'Close People', intensity: 3 },
  { id: '205', text: "What do you think is my biggest strength in life?", category: 'Close People', intensity: 2 },
  { id: '206', text: "What is something that makes me completely unique?", category: 'Close People', intensity: 2 },
  { id: '207', text: "What is something I do that makes me lovable to you?", category: 'Close People', intensity: 3 },
  { id: '208', text: "What is the best way to cheer me up when I'm sad?", category: 'Close People', intensity: 2 },
  { id: '209', text: "What is the best way to calm me down when I'm angry?", category: 'Close People', intensity: 2 },
  { id: '210', text: "If I was a food, what food would I be?", category: 'Close People', intensity: 1 },
  { id: '211', text: "If I was a movie genre, what genre would I be?", category: 'Close People', intensity: 1 },
  { id: '212', text: "What do you think is my biggest, deepest fear?", category: 'Close People', intensity: 3 },
  { id: '213', text: "What do you think is my biggest, wildest dream?", category: 'Close People', intensity: 3 },
  { id: '214', text: "What do you think is a secret wish I have?", category: 'Close People', intensity: 3 },
  { id: '215', text: "What do you think is my deepest regret?", category: 'Close People', intensity: 3 },
  { id: '216', text: "What do you think is my proudest moment so far?", category: 'Close People', intensity: 2 },
  { id: '217', text: "What do you think is my most embarrassing moment?", category: 'Close People', intensity: 2 },
  { id: '218', text: "When do you think I was the happiest?", category: 'Close People', intensity: 3 },
  { id: '219', text: "When do you think I was the saddest?", category: 'Close People', intensity: 3 },
  { id: '220', text: "What would you do if I suddenly moved across the world?", category: 'Close People', intensity: 3 },
  { id: '221', text: "What would you do if I won the lottery tomorrow?", category: 'Close People', intensity: 2 },
  { id: '222', text: "What would you do if I went to jail?", category: 'Close People', intensity: 3 },
  { id: '223', text: "What would you do if I became a massive global celebrity?", category: 'Close People', intensity: 2 },
  { id: '224', text: "What would you do if I completely lost my memory?", category: 'Close People', intensity: 3 },
  { id: '225', text: "What would you do if I suddenly turned evil?", category: 'Close People', intensity: 2 },
  { id: '226', text: "What would you do if I completely changed my name and identity?", category: 'Close People', intensity: 2 },
  { id: '227', text: "If I became a ghost, who would I haunt?", category: 'Close People', intensity: 1 },
  { id: '228', text: "If I became a superhero, what would my power be?", category: 'Close People', intensity: 1 },
  { id: '229', text: "If I became a villain, what would my evil plan be?", category: 'Close People', intensity: 1 },
  { id: '230', text: "If I became the president, what is the first law I'd pass?", category: 'Close People', intensity: 2 },
  { id: '231', text: "If we were in a horror movie, who would die first?", category: 'Close People', intensity: 1 },
  { id: '232', text: "If we were stranded on an island, who would survive longer?", category: 'Close People', intensity: 2 },
  { id: '233', text: "If we were bank robbers, what would be our roles?", category: 'Close People', intensity: 1 },
  { id: '234', text: "What is a song that perfectly describes our relationship?", category: 'Close People', intensity: 2 },
  { id: '235', text: "What is a movie character that reminds you of me?", category: 'Close People', intensity: 1 },
  { id: '236', text: "If I could only wear one outfit forever, what would it be?", category: 'Close People', intensity: 1 },
  { id: '237', text: "What is the most 'me' thing I have ever done?", category: 'Close People', intensity: 2 },
  { id: '238', text: "What is a phrase or word I say way too much?", category: 'Close People', intensity: 1 },
  { id: '239', text: "If you had to describe me in three words, what would they be?", category: 'Close People', intensity: 2 },
  { id: '240', text: "What is something I do that makes you instantly smile?", category: 'Close People', intensity: 3 },

  // --- WOULD YOU RATHER (241-300) ---
  { id: '241', text: "Would you rather have a rewind button or a pause button on your life?", category: 'Would You Rather', intensity: 2 },
  { id: '242', text: "Would you rather know the history of every object you touch or the future of every person you meet?", category: 'Would You Rather', intensity: 3 },
  { id: '243', text: "Would you rather always have to say everything on your mind, or never speak again?", category: 'Would You Rather', intensity: 3 },
  { id: '244', text: "Would you rather be completely invisible or be able to fly?", category: 'Would You Rather', intensity: 1 },
  { id: '245', text: "Would you rather have no internet or no cell phone?", category: 'Would You Rather', intensity: 1 },
  { id: '246', text: "Would you rather always be 10 degrees too hot or 10 degrees too cold?", category: 'Would You Rather', intensity: 1 },
  { id: '247', text: "Would you rather read minds or be able to teleport?", category: 'Would You Rather', intensity: 2 },
  { id: '248', text: "Would you rather breathe underwater or fly?", category: 'Would You Rather', intensity: 1 },
  { id: '249', text: "Would you rather have infinite money or infinite time?", category: 'Would You Rather', intensity: 3 },
  { id: '250', text: "Would you rather never have to sleep or never have to eat?", category: 'Would You Rather', intensity: 2 },
  { id: '251', text: "Would you rather always tell the truth or always have to lie?", category: 'Would You Rather', intensity: 3 },
  { id: '252', text: "Would you rather know exactly when you die or exactly how you die?", category: 'Would You Rather', intensity: 3 },
  { id: '253', text: "Would you rather lose all your money or lose all your memories?", category: 'Would You Rather', intensity: 3 },
  { id: '254', text: "Would you rather be a lonely genius or a joyful simpleton?", category: 'Would You Rather', intensity: 3 },
  { id: '255', text: "Would you rather be incredibly famous or incredibly wealthy?", category: 'Would You Rather', intensity: 2 },
  { id: '256', text: "Would you rather be a loved hero or a feared villain?", category: 'Would You Rather', intensity: 2 },
  { id: '257', text: "Would you rather be a master of all trades or the absolute best at one thing?", category: 'Would You Rather', intensity: 2 },
  { id: '258', text: "Would you rather be a kid forever or an adult forever?", category: 'Would You Rather', intensity: 2 },
  { id: '259', text: "Would you rather eat only pizza forever or eat only burgers forever?", category: 'Would You Rather', intensity: 1 },
  { id: '260', text: "Would you rather drink only water forever or only soda forever?", category: 'Would You Rather', intensity: 1 },
  { id: '261', text: "Would you rather live in the mountains or by the beach?", category: 'Would You Rather', intensity: 1 },
  { id: '262', text: "Would you rather live in a bustling city or deep in the country?", category: 'Would You Rather', intensity: 1 },
  { id: '263', text: "Would you rather live permanently in the past or permanently in the future?", category: 'Would You Rather', intensity: 3 },
  { id: '264', text: "Would you rather live in your favorite movie or your favorite book?", category: 'Would You Rather', intensity: 2 },
  { id: '265', text: "Would you rather be a powerful wizard or a superhero?", category: 'Would You Rather', intensity: 1 },
  { id: '266', text: "Would you rather be a pirate or be a ninja?", category: 'Would You Rather', intensity: 1 },
  { id: '267', text: "Would you rather be a vampire or be a werewolf?", category: 'Would You Rather', intensity: 1 },
  { id: '268', text: "Would you rather be a slow zombie or a noisy ghost?", category: 'Would You Rather', intensity: 1 },
  { id: '269', text: "Would you rather ride a dragon or ride a unicorn?", category: 'Would You Rather', intensity: 1 },
  { id: '270', text: "Would you rather have a pet dog or a pet cat?", category: 'Would You Rather', intensity: 1 },
  { id: '271', text: "Would you rather be a free bird or an ocean fish?", category: 'Would You Rather', intensity: 2 },
  { id: '272', text: "Would you rather be an ancient tree or a mountain rock?", category: 'Would You Rather', intensity: 2 },
  { id: '273', text: "Would you rather have a third arm or a third eye?", category: 'Would You Rather', intensity: 1 },
  { id: '274', text: "Would you rather have a tail or have horns?", category: 'Would You Rather', intensity: 1 },
  { id: '275', text: "Would you rather have wings or have gills?", category: 'Would You Rather', intensity: 1 },
  { id: '276', text: "Would you rather have soft fur or hard scales?", category: 'Would You Rather', intensity: 1 },
  { id: '277', text: "Would you rather have sharp claws or sharp fangs?", category: 'Would You Rather', intensity: 1 },
  { id: '278', text: "Would you rather have a bird's beak or a pig's snout?", category: 'Would You Rather', intensity: 1 },
  { id: '279', text: "Would you rather have a turtle shell or octopus tentacles?", category: 'Would You Rather', intensity: 1 },
  { id: '280', text: "Would you rather have webbed feet or horse hooves?", category: 'Would You Rather', intensity: 1 },
  { id: '281', text: "Would you rather have deer antlers or elephant tusks?", category: 'Would You Rather', intensity: 1 },
  { id: '282', text: "Would you rather have an elephant trunk or a camel hump?", category: 'Would You Rather', intensity: 1 },
  { id: '283', text: "Would you rather have a kangaroo pouch or a lion's mane?", category: 'Would You Rather', intensity: 1 },
  { id: '284', text: "Would you rather have a snake rattle or a bee stinger?", category: 'Would You Rather', intensity: 1 },
  { id: '285', text: "Would you rather have a venomous bite or a poisonous touch?", category: 'Would You Rather', intensity: 1 },
  { id: '286', text: "Would you rather have a sonic scream or a paralyzing gaze?", category: 'Would You Rather', intensity: 2 },
  { id: '287', text: "Would you rather have acid spit or freezing breath?", category: 'Would You Rather', intensity: 2 },
  { id: '288', text: "Would you rather have a healing aura or a destructive aura?", category: 'Would You Rather', intensity: 2 },
  { id: '289', text: "Would you rather have mind control power or telekinetic power?", category: 'Would You Rather', intensity: 3 },
  { id: '290', text: "Would you rather have a shapeshifting power or an illusion power?", category: 'Would You Rather', intensity: 2 },
  { id: '291', text: "Would you rather have a time travel power or a dimensional travel power?", category: 'Would You Rather', intensity: 3 },
  { id: '292', text: "Would you rather have a reality warping power or a life creation power?", category: 'Would You Rather', intensity: 3 },
  { id: '293', text: "Would you rather fight one bear or fight ten wolves?", category: 'Would You Rather', intensity: 2 },
  { id: '294', text: "Would you rather explore space or explore the deep ocean?", category: 'Would You Rather', intensity: 2 },
  { id: '295', text: "Would you rather never feel physical pain or never feel emotional pain?", category: 'Would You Rather', intensity: 3 },
  { id: '296', text: "Would you rather be forced to sing every song you hear or dance to every song you hear?", category: 'Would You Rather', intensity: 1 },
  { id: '297', text: "Would you rather have hands for feet or feet for hands?", category: 'Would You Rather', intensity: 1 },
  { id: '298', text: "Would you rather always feel like you need to sneeze but can't, or always have a pebble in your shoe?", category: 'Would You Rather', intensity: 2 },
  { id: '299', text: "Would you rather give up showering for a month or give up the internet for a month?", category: 'Would You Rather', intensity: 2 },
  { id: '300', text: "Would you rather be stranded on an island alone or with someone you absolutely hate?", category: 'Would You Rather', intensity: 3 },
];
